%% Tension de Red en plano dq
plot(...
    Vdq.Time, Vdq.Data(:,1),...
    Vdq.Time,Vdq.Data(:,2)...
);
grid on;
legend('Vd','Vq');

%% Entrada Trifasica vs Salida Trifasica del Puente
subplot(2,1,1)
plot(...
    v_puente_fase.Time, v_puente_fase.Data(:,1),...
    v_puente_fase.Time,v_puente_fase.Data(:,2),...
    v_puente_fase.Time,v_puente_fase.Data(:,3)...
);
subtitle("Salida del Puente - Tensiones de Fase")

subplot(2,1,2)
plot(...
    v_red_fase.Time, v_red_fase.Data(:,1),...
    v_red_fase.Time,v_red_fase.Data(:,2),...
    v_red_fase.Time,v_red_fase.Data(:,3)...
);
subtitle("Entrada de la red - Tensiones de Fase")

%% Entrada Trifasica vs Salida Trifasica del Puente
% Comparacion fase a fase
subplot(3,1,1)
plot(...
    v_puente_fase.Time, v_puente_fase.Data(:,1),...
    v_red_fase.Time,v_red_fase.Data(:,1)...
);
subtitle("Fase A")

subplot(3,1,2)
plot(...
    v_puente_fase.Time, v_puente_fase.Data(:,2),...
    v_red_fase.Time,v_red_fase.Data(:,2)...
);
subtitle("Fase B")

subplot(3,1,3)
plot(...
    v_puente_fase.Time, v_puente_fase.Data(:,3),...
    v_red_fase.Time,v_red_fase.Data(:,3)...
);
subtitle("Fase C")


%% Vector rotante
plot( ...
    Vabc_alphabeta(:,1), Vabc_alphabeta(:,2), ...
    Vabc_target_alphabeta(:,1), Vabc_target_alphabeta(:,2),...
    Vabc_puente_alphabeta(:,1), Vabc_puente_alphabeta(:,2)...
    )
legend('Red', 'Objetivo segun control', 'Logrado')